{
  "phases": {
    "setup": {
      "nixPkgs": ["nodejs-18_x"]
    },
    "install": {
      "cmds": [
        "cd backend",
        "npm ci"
      ]
    },
    "build": {
      "cmds": [
        "echo 'Build completed'"
      ]
    }
  },
  "start": {
    "cmd": "cd backend && npm run migrate && npm start"
  }
}
